### ISSUE TITLE
High socket recv buffer usage and size

### ISSUE THREAD

**Issue by cbrchrt** [thom311/libnl#104]
Hi,

I have a application that listens to Netlink neighbor events using libnl. When I tested it receiving about 1000 simultaneous NEWNEIGH events, I noticed that my application was missing some of them. 

While debugging it, I could see in /proc/net/netlink that my socket had some drops and that nl_recvmsgs_default was returning -5 (ENOMEM) confirming the missing events. Debugging it further I've found out that libnl is remapping -5 from 105 which is ENOBUFS in the socket recv function. So to fix the problem I had to increase my receive buffer using nl_socket_set_buffer_size and also the Linux limit  (using sysctl net.core.rmem_max) since it was below what I need for nl_socket_set_buffer_size.

So this fixed my problem, but to handle all 1000 events I had to increase the buffer to 2MiB which, according to the SO_RCVBUF documentation, the Kernel effectively doubles it to 4MiB for bookkeeping overhead. This value seems too high since each Netlink event is less that 100 bytes long (about 80 from what I saw in the libnl's debug messages).  So is my buffer size correct for what the number of events I am expecting, the Kernel really needs that much or am I missing something?

Thanks,
CB

**Comment by thom311** [comment]
I don't know the answer to your question, but would be interested in it too.

[NetworkManager](https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/src/platform/nm-linux-platform.c?id=6a8e46700f393ff8c9522dbd90bb30058b9d6d4b#n6351) and [systemd-networkd](https://github.com/systemd/systemd/commit/be660c371b231c253a97464ddd8f32ec8721da21) set the receive buffer to 8 MB. To my understanding, that does not mean that the kernel actually reserves that much memory unless it is needed.

I wasn't aware of net.core.rmem_max. On my system it is set to 208 KB, so maybe that limits the 8 MB above to effectively 416 KB... which however seems sufficient for me.


I am closing this issue for now, as it is more a (valid) question then an issue. This may be better discussed on the mailing list (libnl@lists.infradead.org). Thanks
