### ISSUE TITLE
link: set ifi_change in rtnl_link_build_add_request

### ISSUE THREAD

**Issue by Lusus** [thom311/libnl#111]
Should rtnl_link_build_add_request() (in lib/route/link.c) not also populate ".ifi_changes" of the "ifi" struct? Not populating the mask makes it impossible to to use rtnl_link_add() to unset the IFF_UP flag to bring the interface down (which is supported by the kernel). I found there was a similar issue with rtnl_link_change() before, and the "add" case may have simply been missed when fixing it: [https://github.com/thom311/libnl/commit/34ccb7210f1238f89229c117dc3d28cea7ae00bb](url)

I have found that this change (in bold) resolved the issue for me:

int rtnl_link_build_add_request(struct rtnl_link _link, int flags,
                struct nl_msg *_result)
{
    struct ifinfomsg ifi = {
        .ifi_family = link->l_family,
        .ifi_index = link->l_index,
        .ifi_flags = link->l_flags,
        **.ifi_change = link->l_flag_mask,**
    };

```
return build_link_msg(RTM_NEWLINK, &ifi, link, flags, result);
```

}

I am new to using libnl, so if I am mistaken, I sincerely apologise.

**Comment by thom311** [comment]
I think you are right. thanks for reporting!!!

Should be fixed by commit 6f9620721200d171d6a317573b3c1c00141f036b. Please reopen, if you think something is wrong.

Thanks.
