### ISSUE TITLE
Use of cache manager not working

### ISSUE THREAD

**Issue by Pathjana** [thom311/libnl#118]
Hi,

 I am new user and trying to use the cache manager, and the basic example in the test directory is not working, it is failing nl_cache_mngr_add with the error message of "unknown or invalid cache type" when I am trying to add the cache "route/link" or anything else like "route/addr" etc.

 Can you please let me know what am I missing, I am able to do other things like get a cache dump or get individual link elements etc.

Thanks
jana

**Comment by thom311** [comment]
can you detail which example isn't working, and what are you doing precisely to test it?

Are you linking libnl3 statically? Does dynamic linking fix it?

**Comment by Pathjana** [comment]
I am trying the sample test-cache-mngr.c, and in fact just using the first two functions, i.e. nl_cache_mngr_alloc and nl_cach_mngr_add. I get the error in the nl_cache_mngr_add function.

I am using the dynamic library and I using the following `pkg-config --cflags --libs libnl-route-3.0` and looks like the actual library that gets linked is libnl-3.so.200

I built and installed the whole thing using the link http://www.linuxfromscratch.org/blfs/view/7.9/basicnet/libnl.html
Just not sure what is the difference in my environment and the reason for this failure?

Thanks
Jana

**Comment by thom311** [comment]
sounds like issue https://github.com/thom311/libnl/issues/93

**Comment by Pathjana** [comment]
Yes it is, thanks that fixes it.

**Comment by thom311** [comment]
Cool, thanks for confirming.
