### ISSUE TITLE
nl_recvmsgs() does not inform caller when other end closes connection

### ISSUE THREAD

**Issue by cdprashanth** [thom311/libnl#129]
Hi 
I am new to libnl.
We are using libnl-3.2.22
 i am seeing issue where my app goes to 100% cpu utilization and when i looked further i see that i am getting lots of EPOLLERR in epoll_wait()ing on netlink socket.
we are using non-blocking netlink socket 

I have few queries

1) From comments in nl_recv()

++
nl_recv() 
..

 * This function blocks until data is available to be read unless the socket
 * has been put into non-blocking mode using nl_socket_set_nonblocking() in
 * which case this function will return immediately with a return value of 0.

++
but this comment seems not true when i see code.

Is this old comment and needs to be updated ?

2)  In case where  socket is non-blocking and recvmsg() returns 0 (this happens when we get EPOLLERR on that soket), do libnl APIs inform caller when other end closes connection i.e when recvmsg() inside nl_recv return 0 ?
libnl doesnot seem to have a way to let app know about this case.

Due to this my app does not know about connection closure 

3) Why am i getting EPOLLERR in epoll_wait() on netlink socket ? is this because other side of netlink ie kernel side closed connection ?
even if kernel side closed connection why non-stop repeated EPOLLERR s on netlink sockets ?

Appreciate your comments on this
Thanks
Prashant

**Comment by thom311** [comment]
1.) yes, the documentation is wrong. It's fixed now: https://github.com/thom311/libnl/commit/3dd2a0f26fa59896b4b4a262cf309a4be4aa70d3

The behavior was changed with version 3.2.22: https://github.com/thom311/libnl/commit/375a6294a41e003f873821a01d947f0ecfaf76d4

See for example how [NetworkManager](https://cgit.freedesktop.org/NetworkManager/NetworkManager/tree/src/platform/nm-linux-platform.c&id=22722b77322fb3ddc1a99509340e8175acddb154#n6121) handles this.

2.)

> In case where socket is non-blocking and recvmsg() returns 0 (this happens when we get EPOLLERR on that soket), do libnl APIs inform caller when other end closes connection i.e when recvmsg() inside nl_recv return 0 ?
libnl does not seem to have a way to let app know about this case.

How do you mean "inform"? No, `nl_recv()` is only a wrapper around `recv`. epoll tells you about the state of the file descriptor and whether you can read from it. See the manual for `recv()`.


3.)

> Why am i getting EPOLLERR in epoll_wait() on netlink socket ? is this because other side of netlink ie kernel side closed connection ?
even if kernel side closed connection why non-stop repeated EPOLLERR s on netlink sockets ?

It is a question about how epoll works with netlink sockets. I don't know the details.
