### ISSUE TITLE
genl_connect fails with NLE_EXIST

### ISSUE THREAD

**Issue by cdprashanth** [thom311/libnl#131]
Hi
I am new to libnl.My app uses libnl-3.2.22
We are using netlink with memory map.
In the app, the netlink socket is closed (nl_socket_free() ) on some
error condition and new netlink connection is established.
But I am seeing that genl_connect() is failing with -6 (NLE_EXIST
"Object exists") when i try to create new net link connection.
My guess is this is EADDRINUSE from bind inside genl_connect()
Should i set SO_REUSEADDR  on netlink socket to resolve this error?
Or is this issue fixed in latest libnl version libnl-3.2.29 ?
Could you please help me resolve this issue?
Thanks

**Comment by thom311** [comment]
I don't think that 3.2.29 would change anything in this regard. But it's not hard to test with a newer version. This doesn't ring a bell.

Try strace-ing the application to see which call fails.
