### ISSUE TITLE
nl_recvmsgs return code issue

### ISSUE THREAD

**Issue by cdprashanth** [thom311/libnl#134]
nl_recvmsgs returns success (0) even in case of no data is read (i.e if recvmsg returns 0 )

[ * @return 0 on success or a negative error code from nl_recv(). ]

Then how caller of nl_recvmsgs should get to know about remote close (remote closed is indicated by 0 returned from recvmsg  ) ?
Instead ,nl_recvmsgs () should just return whatever nl_recv returns, so that now callers will get 0 when remote is closed.

**Comment by thom311** [comment]
nl_recvmsg() eventually calls recvmsg() multiple times.

In non-blocking mode, recvmsg() returns 0 when there is nothing to read. From your question, it seems that when the remote side closes, recvmsg() may also return 0 -- thus, that situation is indistinguishable for nl_recv() and nl_recvmsgs(). What do you expect libnl to do about that? If you use non-blocking IO, you need to handle this via something like poll().

If you look at the code, you'll see that nl_recvmsgs() pretty much returns the error code that nl_recv(). But if recvmsg() returns 0, there is no error indicated.
That is, "nl_recvmsgs () should just return whatever nl_recv returns" is already the case.

Maybe you want to use instead nl_recvmsgs_report(), which is basically like nl_recvmsgs() but also returns the number of received messages. Thus you know whether there were *any* messages received.
