### ISSUE TITLE
Private function nl_strerror_l exported in dynamic lib

### ISSUE THREAD

**Issue by zorun** [thom311/libnl#140]
Commit 683f27fbb68ca2028a7b3468f17164d484df2759 ("lib: add utility function nl_strerror_l()") introduced a new helper function `nl_strerror_l`, advertised as private.

But this function is exported in the dynamic lib:

```
$ objdump -T /usr/lib/libnl-route-3.so.200.24.0 | grep nl_strerror
0000000000000000      DF *UND*	0000000000000000  libnl_3_2_29 nl_strerror_l
```

Is this expected?  It seems to cause issues downstream https://bugs.lede-project.org/index.php?do=details&task_id=748 (admittedly, in this case, it looks like bmon was compiled against a different version of libnl-route than the one installed, so it was likely to break)

**Comment by thom311** [comment]
libnl3 is split in a core library (libnl-3.so) and protocol specific libraries (libnl-route-3.so, libnl-genl-3.so).

The latter libraries use code from the core library.

Functionsl ike `nl_strerror` or `__flags2str` are not in public headers (they are considered private API), but are exported to be of use for the other libraries.

That may not be the nicest solution, but the other solutions have their own downsides. Maybe internal the code that is shared by mutliple libraries should be linked statically instead.

In the referenced bug, the user only updates libnl-route-3, but not libnl-3. That cannot work as it is, as libnl-route-3.so depends on libnl-3.so. It is not intended that you can combine the libraries of differing versions. That is not only the case of internal API like nl_strerror(). libnl-3.so could likewise add a new public symbol that is required by libnl-route-3.so, resulting in the same problem.
As libnl3 has symbol versioning, the packaging system should generate appropriate dependencies.

**Comment by zorun** [comment]
Ok, thanks for the explanation!
