### ISSUE TITLE
NLE_OBJ_NOTFOUND

### ISSUE THREAD

**Issue by cdprashanth** [thom311/libnl#143]
Hi
I am getting NLE_OBJ_NOTFOUND (-12) on  nl_recvmsgs_default ()
This does not happen always.
how to debug to find root cause for this ?
Thanks

**Comment by thom311** [comment]
NLE_OBJ_NOTFOUND is likely the response from kernel to a request you make. I would run the application with `strace` to see which syscall fails.

Alternatively, set `NLDBG=100` environment variable and see if it reveals useful info.

Alternatively, use a debugger and singlestep through the program.

Alternatively, build libnl from source and add additional debug logging (printf-debugging)


good luck
