### ISSUE TITLE
Fedora has netem delay distributions in /usr/lib64/tc/

### ISSUE THREAD

**Issue by stv0g** [thom311/libnl#148]
libnl3-route only searches in:

```c
/* Check several locations for the dist file */
	char *test_path[] = { "", "./", "/usr/lib/tc/", "/usr/local/lib/tc/" };
```
See: https://github.com/thom311/libnl/blob/master/lib/route/qdisc/netem.c#L895

Should we add lib64 versions?

**Comment by thom311** [comment]
Yes, I think so.

seems on Fedora, iproute-tc installs `/usr/lib64/tc/pareto.dist`.

Probably, it is the job of downstream/distro to patch the path. However, upstream should make it simple, for example by providing a configure option (or maybe just hard-code the lib4 paths).

**Comment by thom311** [comment]
how about 69b730e23e79adb8f38fff018c2b108b9ca9cfb7 ?

Closing, please reopen if there is an issue left. Thanks.

**Comment by stv0g** [comment]
Thanks, this should fix it :)
