### ISSUE TITLE
rtnl_link_change returns NLE_SEQ_MISMATCH

### ISSUE THREAD

**Issue by Tuetuopay** [thom311/libnl#179]
Context: I am trying to set the MAC address of an interface using `rtnl_link_change`.  Here is the relevant snippet:

```cpp
int Foo::bar(struct rtnl_link *link, struct nl_addr *laddr) {
    struct rtnl_link *newlink = rtnl_link_alloc();
    if (newlink == NULL)
        return NLE_NOMEM;
    rtnl_link_set_addr(newlink, laddr);
    return rtnl_link_change(this->nl_sock, link, newlink, NLM_F_CREATE | NLM_F_REPLACE);
}
```

I am consistently getting `NLE_SEQ_MISMATCH` out of this, but it is successful, as my interface's MAC is definitely changed. `rtnl_link_change` is documented to resend the message as a `RTM_SETLINK` for compatibility reasons if `RTM_NEWLINK` yields a `NLE_OPNOTSUPP`. Indeed, the following simpler code always returns a not supported error:

```cpp
int Foo::bar(struct rtnl_link *link, struct nl_addr *laddr) {
    rtnl_link_set_addr(link, laddr);
    return rtnl_link_add(this->nl_sock, link, NLM_F_CREATE | NLM_F_REPLACE);
}
```

From the implementation of `rtnl_link_change`, there is indeed a discrepancy in sequence numbers when retrying to send the message. Each attempt uses `nl_send_auto`, which increments the sequence number of the socket. However, the sequence number of the message itself is *not* incremented, which leads to the incoherency. It was set by the first call to `nl_send_auto` which calls `nl_complete_msg`, but it will not set it again on second call since it has already been set.

The easiest way would be resetting `nlmsg_seq` to `NL_AUTO_SEQ` in the message headers when setting the message type to `RTM_SETLINK`.

I am willing to submit a PR, and will ignore the error for now u_u

**Comment by thom311** [comment]
What you say, sounds right.

Maybe also add an assertion:
```diff
diff --git i/lib/route/link.c w/lib/route/link.c
index de3c393d..72f85445 100644
--- i/lib/route/link.c
+++ w/lib/route/link.c
@@ -1784,6 +1784,7 @@ int rtnl_link_change(struct nl_sock *sk, struct rtnl_link *orig,
         if (err < 0)
                  return err;
 
+        BUG_ON(msg->nm_nlh->nlmsg_seq != NL_AUTO_SEQ);
 retry:
         err = nl_send_auto_complete(sk, msg);
         if (err < 0)
```

Can you send a pull-request? Thanks

**Comment by thom311** [comment]
and maybe add a doc comment, that advices to ignore `NLE_OPNOTSUPP`, to make it working with older versions.

**Comment by Tuetuopay** [comment]
I don't quite get your answer. Are you suggesting keeping the old behaviour for backwards compatibility (which is reasonable for such a library).

Furthermore, I don't quite get your patch, as the assertion would always be verified as the `NL_AUTO_SEQ` is set by the `rtnl_link_build_change_request` function, just above. And if you put it just after the `retry` label, it would always fail on the second change attempt (i.e. when `RTM_NEWLINK` fails).

IMO the easiest fix would be the following:

```diff
diff --git a/lib/route/link.c b/lib/route/link.c
index de3c393..d04e517 100644
--- a/lib/route/link.c
+++ b/lib/route/link.c
@@ -1792,6 +1792,7 @@ retry:
        err = wait_for_ack(sk);
        if (err == -NLE_OPNOTSUPP && msg->nm_nlh->nlmsg_type == RTM_NEWLINK) {
                msg->nm_nlh->nlmsg_type = RTM_SETLINK;
+               msg->nm_nlh->nlmsg_seq = NL_AUTO_SEQ;
                goto retry;
        }
```

Then, in case of tailure, the message's own sequence number is reset to `NL_AUTO_SEQ`, to be synchronised again to the socket's own one by `nl_send_auto_complete` (calls `nl_send_auto` which calls `nl_complete_msg` which sets the message's sequence number).

**Comment by Tuetuopay** [comment]
I can confirm the above proposed patch works. PR incomig!

**Comment by thom311** [comment]
> I don't quite get your answer. Are you suggesting keeping the old behaviour for backwards compatibility 
> (which is reasonable for such a library)?

No, while error codes are part of API and changing them is an API change, in this case it's just a bug. I doubt that fixing this bug would break existing code (but who knows).

> Furthermore, I don't quite get your patch, as the assertion would always be verified as the
> NL_AUTO_SEQ is set by the rtnl_link_build_change_request function, just above.

Not sure what you mean. `BUG_ON()` is an assertion, and that is *supposed* to always succeed.

I think your patch from #184 is good. Merged with two minor follow-up-fixes.

Closing.

Thank you!!
