### ISSUE TITLE
cant install on darwin I get 

### ISSUE THREAD

**Issue by charlieporth1** [thom311/libnl#181]
And my Makefile is empty

```-------------------------------------------------------------------------------
                                  NOTE

 There have been some changes starting with 3.2 regarding where and how libnl
 is being installed on the system in order to allow multiple libnl versions
 to be installed in parallel:

    - Headers will be installed in ${prefix}/include/libnl3, therefore
      you will need to add "-I/usr/include/libnl3" to CFLAGS

    - The library basename was renamed to libnl-3, i.e. the SO names become
      libnl-3.so., libnl-route-3.so, etc.

    - libtool versioning was assumed, to ease detection of compatible library
      versions.

 If you are using pkg-config for detecting and linking against the library 
 things will continue magically as if nothing every happened. If you are 
 linking manually you need to adapt your Makefiles or switch to using 
 pkg-config files.

-------------------------------------------------------------------------------

**Comment by thom311** [comment]
I think there is not enough information to understand what you are doing. Also, the comment you quote doesn't sound related. Yes, `./configure` prints this at the end (it's informational only, but it's not clear how this relates to your issue).

If you build from git, you commonly need to run `autoreconf` first -- or just executure `./autogen.sh` script. Did you do that?

**Comment by charlieporth1** [comment]
I build from git, yes but I'm on OSX and I dont think its installing properly is there a way to detect if its installed?

**Comment by thom311** [comment]
the warning doesn't seem related either, I get that too.

What makes you think it is not properly installed? In general, building is

```
./autogen.sh
./configure --prefix=/some/where/etc/pp
make
sudo make install
```

I don't have OSX, nor do I have any idea whether netlink or libnl3 is gonna work there (I would think not). Are you trying to do this, because you want to build an application that uses libnl3? Then, maybe, you wanna ask how seek help how that application can be installed on OSX.

**Comment by charlieporth1** [comment]
@thom311  I was using these instructions [this](http://www.linuxfromscratch.org/blfs/view/svn/basicnet/libnl.html)

**Comment by thom311** [comment]
I don't think that `iw` works on OSX, same for `libnl3`. At least that is what quick googeling suggests to me, but I don't know.

The instructions you quote are for Linux, they may not apply to OSX directly. Good luck :)

**Comment by Tuetuopay** [comment]
Netlink is a Linux-specific API. macOS is based on BSD and has its own API (not socket based) to control the whole kernel called Kernel Control API, with NKE being the equivalent of Netlink. So sadly neither of `iw` nor `libnl3` would work on macOS.

Hope this helps :)

**Comment by thom311** [comment]
Thanks for confirming. I think this issue can be closed.
