### ISSUE TITLE
libnl Compatiblility with kernel verison

### ISSUE THREAD

**Issue by subhajitchatu** [thom311/libnl#203]
1. Is there any dependency between libnl and kernel version? I am using kernel version 4.1. What is the stable and suitable version of recommended libnl version for this kernel?

2. Is the latest libnl version compatible with older kernel verions 3.x or do we need to select 3.2.25 for this?

**Comment by thom311** [comment]
libnl3 is supposed to work basically with every kernel version. That is, because kernel's netlink API is supposed to be backward compatible and forward compatible (as much as possible).

3.2.25 is very old. I would think, you should always use recent libnl3 releases.

If you have issues, please open a bug. Thank you

**Comment by subhajitchatu** [comment]
Sorry for reopening the issue.

We are facing an issue while programming routes in kernel  4.1.0 using libnl 3.2.25.

On programming around 10k routes in kernel, kernel crashes with following log. The number of routes on which this crash comes varies. However, when routes are programmed using iproute2 package of the same kernel version, this crash comes after 1 lac routes.

Is it possible that this issue is coming due to different headers of kernel 4.1.0 & libnl 3.2.25?

Log:

Unable to handle kernel paging request at virtual address d07d1018 
pgd = cc635b80 
[d07d1018] *pgd=80000000007003, *pmd=096fb003, *pte=00000000 
Internal error: Oops: 207 [#1] SMP ARM 
Modules linked in: epldchar(O) mvPpDrv(O) mvKernelExt(O) 
CPU: 3 PID: 4842 Comm: route Tainted: G O 4.1.0 
#1 task: c9f22540 ti: c8562000 task.ti: c8562000 
PC is at leaf_walk_rcu+0xa8/0x134 
LR is at fib_route_seq_next+0x44/0x80 
pc : [<c04932dc>] lr : [<c04934a8>] psr: 60000013 
sp : c8563e88 ip : 00000007 fp : c9e061f4 
r10: 00000000 r9 : 00000400 r8 : c8563f80 
r7 : c9df9280 r6 : c94fa500 r5 : 00000001 r4 : 00000040 
r3 : d07d1014 r2 : 012aa000 r1 : 00000042 r0 : c94fa508 
Flags: nZCv IRQs on FIQs on Mode SVC_32 ISA ARM Segment user 
Control: 30c5387d Table: 0c635b80 DAC: 00000000 
Process route (pid: 4842, stack limit = 0xc8562220) 
Stack: (0xc8563e88 to 0xc8564000) 
3e80: 00002a73 00000000 c90d2180 00000180 00000000 c0109d20 
3ea0: b6fbb000 c90d21b0 00002a72 00000000 00002a73 00000000 00000001 00000000 
3ec0: 00000001 00000000 00000000 cc643f80 b6fbb000 00000000 00000000 c013e2e4 
3ee0: c055aa40 b6fbb000 c9df9280 c8563f80 00000400 c00e90b8 ffffffff 00000000 
3f00: c075c0a4 00000100 c8562000 c8563f20 c8562000 00000000 c075c0a4 c002af84 
3f20: 65148100 00000203 c075c080 c0754308 0000000a c07aa500 c075c100 c9df9280 
3f40: c9df9280 b6fbb000 c8563f80 c9df9280 00000400 c00e9840 00000001 cc407000 
3f60: c9f22540 00153800 00000000 c9df9280 c9df9280 00000400 b6fbb000 c00ea0d4 
3f80: 00153800 00000000 000003ff 0001e050 0001e050 0001e050 00000003 c00100c4 
3fa0: c8562000 c000ff40 0001e050 0001e050 00000003 b6fbb000 00000400 00000000 
3fc0: 0001e050 0001e050 0001e050 00000003 beb602b8 0000000a beb602b8 00000000 
3fe0: 00000000 beb5ffa4 48197a78 481ebb5c 60000010 00000003 00000000 00000000 
[<c04932dc>] (leaf_walk_rcu) from [<c04934a8>] (fib_route_seq_next+0x44/0x80) 
[<c04934a8>] (fib_route_seq_next) from [<c0109d20>] (seq_read+0x2a4/0x468) 
[<c0109d20>] (seq_read) from [<c013e2e4>] (proc_reg_read+0x5c/0x84) 
[<c013e2e4>] (proc_reg_read) from [<c00e90b8>] (__vfs_read+0x24/0xd0) 
[<c00e90b8>] (__vfs_read) from [<c00e9840>] (vfs_read+0x7c/0x108) 
[<c00e9840>] (vfs_read) from [<c00ea0d4>] (SyS_read+0x40/0x94) 
[<c00ea0d4>] (SyS_read) from [<c000ff40>] (ret_fast_syscall+0x0/0x3c) 
Code: e1540215 3a000010 e5932000 e5133004 (e5d3c004) 
---[ end trace c2555849a6fc6357 ]--- 
Kernel panic - not syncing: Fatal exception 
CPU0: stopping 
CPU: 0 PID: 1288 Comm: in:imuxsock Tainted: G D O 4.1.0 #1 
[<c0017974>] (unwind_backtrace) from [<c00135cc>] (show_stack+0x10/0x14) 
[<c00135cc>] (show_stack) from [<c05495d0>] (dump_stack+0x84/0x94) 
[<c05495d0>] (dump_stack) from [<c00165c4>] (handle_IPI+0x144/0x170) 
Exception stack(0xc9e15df8 to 0xc9e15e40) 
5de0: 00000000 b6e175e8 
5e00: 00000000 c9e15e70 c9e15f6c c9e15e74 b6e175b0 00000001 b6e175f8 b6e17604 
5e20: 00000000 b6e175c8 00000000 c9e15e40 c03fafc8 c03facc4 60000013 ffffffff 
[<c00140c0>] (__irq_svc) from [<c03facc4>] (copy_msghdr_from_user+0x7c/0x174) 
[<c03facc4>] (copy_msghdr_from_user) from [<c03fafc8>] (___sys_recvmsg+0x38/0x11c) 
[<c03fafc8>] (___sys_recvmsg) from [<c03fbcfc>] (__sys_recvmsg+0x3c/0x6c) 
[<c03fbcfc>] (__sys_recvmsg) from [<c000ff40>] (ret_fast_syscall+0x0/0x3c) 
CPU2: stopping 
CPU: 2 PID: 1754 Comm: evHndl_9 Tainted: G D O 4.1.0 #1 
[<c0017974>] (unwind_backtrace) from [<c00135cc>] (show_stack+0x10/0x14) 
[<c00135cc>] (show_stack) from [<c05495d0>] (dump_stack+0x84/0x94) 
[<c05495d0>] (dump_stack) from [<c00165c4>] (handle_IPI+0x144/0x170) 
Exception stack(0xc9175da0 to 0xc9175de8) 
5da0: ffedf3e3 afdbed58 0000002a 00000000 0000002a 0000002a c9175f04 ffedf40d 
5dc0: ffedf000 00000000 c0558180 00000000 00000000 c9175dec c027c90c c026aad4 
5de0: 20000013 ffffffff 
[<c00140c0>] (__irq_svc) from [<c026aad4>] (__copy_from_user+0x8/0x3b4) 
[<c026aad4>] (__copy_from_user) from [<c027c90c>] (iov_iter_copy_from_user_atomic+0x64/0x20)
[<c027c90c>] (iov_iter_copy_from_user_atomic) from [<c00a77ac>] (generic_perform_write+0xdc)
[<c00a77ac>] (generic_perform_write) from [<c00a8860>] (__generic_file_write_iter+0x164/0x1)
[<c00a8860>] (__generic_file_write_iter) from [<c00a89fc>] (generic_file_write_iter+0x14c/0)
[<c00a89fc>] (generic_file_write_iter) from [<c00e920c>] (__vfs_write+0xa8/0xd8) 
[<c00e920c>] (__vfs_write) from [<c00e9960>] (vfs_write+0x94/0x154) 
[<c00e9960>] (vfs_write) from [<c00ea168>] (SyS_write+0x40/0x94) 
[<c00ea168>] (SyS_write) from [<c000ff40>] (ret_fast_syscall+0x0/0x3c) 
CPU1: stopping 
CPU: 1 PID: 1297 Comm: rs:main Q:Reg Tainted: G D O 4.1.0 #1 
[<c0017974>] (unwind_backtrace) from [<c00135cc>] (show_stack+0x10/0x14) 
[<c00135cc>] (show_stack) from [<c05495d0>] (dump_stack+0x84/0x94) 
[<c05495d0>] (dump_stack) from [<c00165c4>] (handle_IPI+0x144/0x170) 
Exception stack(0xc9e65ee8 to 0xc9e65f30) 
5ee0: cc7440c0 cc6fe580 c9e64000 00005fb7 c07577c0 00000000 
5f00: ca7bc7c0 0a065000 cc7440c0 00000001 cc6fe580 c9e65f4c 00000000 c9e65f30 
5f20: c054a974 c0044de0 60000013 ffffffff 
[<c00140c0>] (__irq_svc) from [<c0044de0>] (finish_task_switch+0x7c/0x120) 
[<c0044de0>] (finish_task_switch) from [<c054a974>] (__schedule+0x1c8/0x52c) 
[<c054a974>] (__schedule) from [<c054ad18>] (schedule+0x40/0x98) 
[<c054ad18>] (schedule) from [<c0012f74>] (do_work_pending+0x24/0xa0) 
[<c0012f74>] (do_work_pending) from [<c000ff8c>] (work_pending+0xc/0x20) 
Rebooting in 3 seconds.. 
BootROM 1.20 
Booting from SPI flash
