### ISSUE TITLE
kernel 4.1.0 crash in route programming using libnl 3.2.25

### ISSUE THREAD

**Issue by subhajitchatu** [thom311/libnl#204]
We are facing an issue while programming routes in kernel 4.1.0 using libnl 3.2.25.

On programming around 10k routes in kernel, kernel crashes with following log. The number of routes on which this crash comes varies. However, when routes are programmed using iproute2 package of the same kernel version, this crash comes after 1 lac routes.

Is it possible that this issue is coming due to different headers of kernel 4.1.0 & libnl 3.2.25?

Log:

Unable to handle kernel paging request at virtual address d07d1018
pgd = cc635b80
[d07d1018] *pgd=80000000007003, *pmd=096fb003, *pte=00000000
Internal error: Oops: 207 [#1] SMP ARM
Modules linked in: epldchar(O) mvPpDrv(O) mvKernelExt(O)
CPU: 3 PID: 4842 Comm: route Tainted: G O 4.1.0
#1 task: c9f22540 ti: c8562000 task.ti: c8562000
PC is at leaf_walk_rcu+0xa8/0x134
LR is at fib_route_seq_next+0x44/0x80
pc : [] lr : [] psr: 60000013
sp : c8563e88 ip : 00000007 fp : c9e061f4
r10: 00000000 r9 : 00000400 r8 : c8563f80
r7 : c9df9280 r6 : c94fa500 r5 : 00000001 r4 : 00000040
r3 : d07d1014 r2 : 012aa000 r1 : 00000042 r0 : c94fa508
Flags: nZCv IRQs on FIQs on Mode SVC_32 ISA ARM Segment user
Control: 30c5387d Table: 0c635b80 DAC: 00000000
Process route (pid: 4842, stack limit = 0xc8562220)
Stack: (0xc8563e88 to 0xc8564000)
3e80: 00002a73 00000000 c90d2180 00000180 00000000 c0109d20
3ea0: b6fbb000 c90d21b0 00002a72 00000000 00002a73 00000000 00000001 00000000
3ec0: 00000001 00000000 00000000 cc643f80 b6fbb000 00000000 00000000 c013e2e4
3ee0: c055aa40 b6fbb000 c9df9280 c8563f80 00000400 c00e90b8 ffffffff 00000000
3f00: c075c0a4 00000100 c8562000 c8563f20 c8562000 00000000 c075c0a4 c002af84
3f20: 65148100 00000203 c075c080 c0754308 0000000a c07aa500 c075c100 c9df9280
3f40: c9df9280 b6fbb000 c8563f80 c9df9280 00000400 c00e9840 00000001 cc407000
3f60: c9f22540 00153800 00000000 c9df9280 c9df9280 00000400 b6fbb000 c00ea0d4
3f80: 00153800 00000000 000003ff 0001e050 0001e050 0001e050 00000003 c00100c4
3fa0: c8562000 c000ff40 0001e050 0001e050 00000003 b6fbb000 00000400 00000000
3fc0: 0001e050 0001e050 0001e050 00000003 beb602b8 0000000a beb602b8 00000000
3fe0: 00000000 beb5ffa4 48197a78 481ebb5c 60000010 00000003 00000000 00000000
[] (leaf_walk_rcu) from [] (fib_route_seq_next+0x44/0x80)
[] (fib_route_seq_next) from [] (seq_read+0x2a4/0x468)
[] (seq_read) from [] (proc_reg_read+0x5c/0x84)
[] (proc_reg_read) from [] (__vfs_read+0x24/0xd0)
[] (__vfs_read) from [] (vfs_read+0x7c/0x108)
[] (vfs_read) from [] (SyS_read+0x40/0x94)
[] (SyS_read) from [] (ret_fast_syscall+0x0/0x3c)
Code: e1540215 3a000010 e5932000 e5133004 (e5d3c004)
---[ end trace c2555849a6fc6357 ]---
Kernel panic - not syncing: Fatal exception
CPU0: stopping
CPU: 0 PID: 1288 Comm: in:imuxsock Tainted: G D O 4.1.0 #1
[] (unwind_backtrace) from [] (show_stack+0x10/0x14)
[] (show_stack) from [] (dump_stack+0x84/0x94)
[] (dump_stack) from [] (handle_IPI+0x144/0x170)
Exception stack(0xc9e15df8 to 0xc9e15e40)
5de0: 00000000 b6e175e8
5e00: 00000000 c9e15e70 c9e15f6c c9e15e74 b6e175b0 00000001 b6e175f8 b6e17604
5e20: 00000000 b6e175c8 00000000 c9e15e40 c03fafc8 c03facc4 60000013 ffffffff
[] (__irq_svc) from [] (copy_msghdr_from_user+0x7c/0x174)
[] (copy_msghdr_from_user) from [] (___sys_recvmsg+0x38/0x11c)
[] (___sys_recvmsg) from [] (__sys_recvmsg+0x3c/0x6c)
[] (__sys_recvmsg) from [] (ret_fast_syscall+0x0/0x3c)
CPU2: stopping
CPU: 2 PID: 1754 Comm: evHndl_9 Tainted: G D O 4.1.0 #1
[] (unwind_backtrace) from [] (show_stack+0x10/0x14)
[] (show_stack) from [] (dump_stack+0x84/0x94)
[] (dump_stack) from [] (handle_IPI+0x144/0x170)
Exception stack(0xc9175da0 to 0xc9175de8)
5da0: ffedf3e3 afdbed58 0000002a 00000000 0000002a 0000002a c9175f04 ffedf40d
5dc0: ffedf000 00000000 c0558180 00000000 00000000 c9175dec c027c90c c026aad4
5de0: 20000013 ffffffff
[] (__irq_svc) from [] (__copy_from_user+0x8/0x3b4)
[] (__copy_from_user) from [] (iov_iter_copy_from_user_atomic+0x64/0x20)
[] (iov_iter_copy_from_user_atomic) from [] (generic_perform_write+0xdc)
[] (generic_perform_write) from [] (__generic_file_write_iter+0x164/0x1)
[] (__generic_file_write_iter) from [] (generic_file_write_iter+0x14c/0)
[] (generic_file_write_iter) from [] (__vfs_write+0xa8/0xd8)
[] (__vfs_write) from [] (vfs_write+0x94/0x154)
[] (vfs_write) from [] (SyS_write+0x40/0x94)
[] (SyS_write) from [] (ret_fast_syscall+0x0/0x3c)
CPU1: stopping
CPU: 1 PID: 1297 Comm: rs:main Q:Reg Tainted: G D O 4.1.0 #1
[] (unwind_backtrace) from [] (show_stack+0x10/0x14)
[] (show_stack) from [] (dump_stack+0x84/0x94)
[] (dump_stack) from [] (handle_IPI+0x144/0x170)
Exception stack(0xc9e65ee8 to 0xc9e65f30)
5ee0: cc7440c0 cc6fe580 c9e64000 00005fb7 c07577c0 00000000
5f00: ca7bc7c0 0a065000 cc7440c0 00000001 cc6fe580 c9e65f4c 00000000 c9e65f30
5f20: c054a974 c0044de0 60000013 ffffffff
[] (__irq_svc) from [] (finish_task_switch+0x7c/0x120)
[] (finish_task_switch) from [] (__schedule+0x1c8/0x52c)
[] (__schedule) from [] (schedule+0x40/0x98)
[] (schedule) from [] (do_work_pending+0x24/0xa0)
[] (do_work_pending) from [] (work_pending+0xc/0x20)
Rebooting in 3 seconds..
BootROM 1.20
Booting from SPI flash

_Originally posted by @thom311 in https://github.com/thom311/libnl/issues/203#issuecomment-434186714_

**Comment by thom311** [comment]
A kernel crash is always a bug in kernel (and must be fixed there).

Yes, libnl3 carries it's own copy of kernel headers, so that it can build also on systems where an older kernel is present.

There may or may not be issues with particular combinations, but these would be bugs that need to be reported. When libnl3 is newer than the kernel, then libnl3 will try to handle the old kernel gracefully (possibly by just some functionality not being available). In the other direction, kernel provides a backward compatible (netlink) API. If libnl3's kernel header are older than your kernel, then it just means that kernel must be backward compatible against that (and it's supposed to work just fine).

In no case, kernel (or libnl3) should crash due to that.

**Comment by subhajitchatu** [comment]
100000(100k) routes can be programmed using iproute2, but with libnl kernel crashed after 10000(10k) routes.

**Comment by thom311** [comment]
ah, interesting: https://en.wikipedia.org/wiki/Lakh

It doesn't seem remarkably different to me whether its 10k or 100k, if it crashes both ways. Anyway, kernel crash is always kernel bug. One might reason, what user-space can do to avoid the crash, but the right course of action is to fix it.

**Comment by subhajitchatu** [comment]
So u don't think this is related to the version delendency of libnl with kernel? We thought there might be some relation between libnl and kernel. Yes, kernel crashes in both libnl and iproute2 but the difference is in the number of routes. However, I am going to try this case with latest libnl version 3.4.0. let's see what happens in that case.
 
Thanks
