### ISSUE TITLE
nl_cache_dump_filter - params is NOT optional -> undefined behaviour

### ISSUE THREAD

**Issue by Inrin** [thom311/libnl#206]
Reference
--------------
https://github.com/thom311/libnl/blob/08160f0555f988db1ec3de65fa188a9d48ebff9d/lib/cache.c#L1210

Problem
-----------
The documentation implies that `params` is **optional** aka can be set to `NULL`.
Gets into undefined behaviour and segfaults.

Thoughts
-------------
`nl_cache_dump_filter` handles this case here https://github.com/thom311/libnl/blob/08160f0555f988db1ec3de65fa188a9d48ebff9d/lib/cache.c#L1220 and here https://github.com/thom311/libnl/blob/08160f0555f988db1ec3de65fa188a9d48ebff9d/lib/cache.c#L1237
I guessed the *optional* is not just a typo meant for the `filter` parameter as `nl_cache_dump` uses it that way.

Now if you execute https://github.com/thom311/libnl/blob/08160f0555f988db1ec3de65fa188a9d48ebff9d/lib/cache.c#L1245
`params` gets accessed without a NULL-check thus de-referencing a NULL-Pointer.
https://github.com/thom311/libnl/blob/08160f0555f988db1ec3de65fa188a9d48ebff9d/lib/utils.c#L1135

Conclusion/Suggestion
-------------------------------
Either make `params` not optional but `filter` or propagate your `params`-can-be-null-logic
further down.

**Comment by thom311** [comment]
fixed in master. thank you!!
