### ISSUE TITLE
Setting interface status of bridges is broken

### ISSUE THREAD

**Issue by firetwister** [thom311/libnl#212]
commit 55bc931a7272e6ac8f555bcc2a373eb2b6b58377 broke setting the link status of a bridge interface. 
I attached a testcase that results in:
Failed to set bridge to up: Operation not supported

[test-bridge-up.c.txt](https://github.com/thom311/libnl/files/2964995/test-bridge-up.c.txt)

**Comment by thom311** [comment]
I think this is fixed by 3c427d0f4fcca91a661d85d21cdea89d41271c6c.

Closing. Please reopen if issue is not fixed. Thanks.
