### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [thom311/libnl#217]
I think that it would be good to make new release with updated code base :)

**Comment by vorner** [comment]
I'd appreciate a release too. I've just hit the bug in https://github.com/thom311/libnl/commit/123dc07bcc3f402a500edf370d2000e171c91b34, which seems to still not be released?

**Comment by TsarVladislav** [comment]
Is there anything that can explain why last release was in 2017? just like @vorner, i faced bug that was already fixed https://github.com/thom311/libnl/commit/3c427d0f4fcca91a661d85d21cdea89d41271c6c , it's just frustrating.

**Comment by thom311** [comment]
The explanation is very mundane: I was busy and didn't take the time. Sorry for that.

A release will happen soon and I'll try to do better in the future.

**Comment by thom311** [comment]
Here: https://github.com/thom311/libnl/releases/tag/libnl3_5_0

See the announce-email: http://lists.infradead.org/pipermail/libnl/2019-September/002415.html

Let me quote/highlight:

> In the past, I would have done a 3.5.0-rc1 release candidate first. But
> this time, I figured to just do the release right away. I expect that
> there should be no problems, but if there are, we can quickly do a
> 3.6.0 bugfix follow-up. That means that you don't want to roll this out
> in a critical environment without testing first. Or said differently:
> if you don't want to test it, you might want to wait to see whether
> critical issues get discovered.
