### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [thom311/libnl#225]
It is possible to have a new version?
The last is from 2017.

**Comment by thom311** [comment]
Here: https://github.com/thom311/libnl/releases/tag/libnl3_5_0

See the announce-email: http://lists.infradead.org/pipermail/libnl/2019-September/002415.html

Let me quote/highlight:

> In the past, I would have done a 3.5.0-rc1 release candidate first. But
> this time, I figured to just do the release right away. I expect that
> there should be no problems, but if there are, we can quickly do a
> 3.6.0 bugfix follow-up. That means that you don't want to roll this out
> in a critical environment without testing first. Or said differently:
> if you don't want to test it, you might want to wait to see whether
> critical issues get discovered.

**Comment by Neustradamus** [comment]
Thanks a lot, I am very happy to have a quickly reply and this the long awaited new release :)
