### ISSUE TITLE
Memory leak in  rtnl_link_alloc_cache() and nl_cache_free()

### ISSUE THREAD

**Issue by subhajitchatu** [thom311/libnl#227]
Hi,

We were trying to fetch rtnl_link object for a particular interface using "rtnl_link_alloc_cache()" and "rtnl_link_get_by_name()". However, we have observed memory leak when we were trying to free nl_cache in case no such link object was found.

The memory leak will become prominent when we run the above operations in while(1) loop as described in the below code segment.

The attached sample program was run on different machines and following were the observations based on different Linux kernel and Libnl versions.

Memory Leak Found:

1. Linux Version: 4.1.0 , Libnl: 3.2.25
2. Linux Version: 3.10.60 , Libnl: 3.2.25
3. Linux Version: 4.0.5 , Libnl: 3.2.25

Memory Leak Not Found:

1. Linux Version: 4.15.0 , Libnl: 3.2.25
2. Linux Version: 3.10.61 , Libnl: 3.2.27
3. Linux Version: 4.9.75 , Libnl: 3.2.29

/*******************************************************************/

`#include<stdio.h>`
`#include<stdlib.h>`
`#include <unistd.h>`
`#include <sys/socket.h>`
`#include <arpa/inet.h>`
`#include <errno.h>`
`#include <net/if_arp.h>`
`#include <linux/if_packet.h>`
`#include <netinet/icmp6.h>`
`#include <netlink/addr.h>`
`#include <netlink/types.h>`
`#include <netlink/route/link.h>`
`#include <netlink/route/neighbour.h>`
`#include <netlink/route/neightbl.h>`
`#include <netlink/route/route.h>`

`int main(int argc, char **argv)`
`{`
  `struct nl_cache *link_cache = NULL;`
  `struct rtnl_link *link = NULL;`
  `int ret_code = 0;`
  `struct nl_sock *sock = NULL;`

  `/**`
  ` * Open a netlink socket for route programming.`
   `*/`
  `sock = nl_socket_alloc();`

  `if (sock == NULL)`
  `{`
    `printf("\nnl_socket_alloc failed");`
    `goto EXIT_LABEL;`
  `}`

  `printf("\nnl_socket_alloc success");`

  `ret_code = nl_connect(sock, NETLINK_ROUTE);`

  `if (ret_code < 0)`
  `{`
    `printf("\nnl_connect failed. ret_code = %d", ret_code);`
    `goto EXIT_LABEL;`
  `}`

 `printf("\nnl_connect success");`

  `while(1)`
  `{`
    `ret_code = rtnl_link_alloc_cache(sock, AF_UNSPEC, &link_cache);`

    if (ret_code < 0)
    {
      printf("\nfailed to allocate cache");
      goto EXIT_LABEL;
    }

    link = rtnl_link_get_by_name(link_cache, "abcd");

    if (link == NULL)
    {
      printf("\nmatching link not found");
      nl_cache_free(link_cache);
      usleep(2000);
    }

    else
    {
      printf("\nmatching link found");
      break;
    }

  `}//end while(1)`

`EXIT_LABEL:`

  `printf("\nReturning with ret_code = %d", ret_code);`

  `return 0;`

`}`

/******************************************************************/

Please let me know the get around of this issue.

Thanks & Regards,
Subhajit Chatterjee

**Comment by thom311** [comment]
see the implementation for `rtnl_link_get_by_name()` [here](https://github.com/thom311/libnl/blob/master/lib/route/link.c#L1326).

Also, the doc string says:
```
 * @attention The reference counter of the returned link object will be
 *            incremented. Use rtnl_link_put() to release the reference.
```

You need to unref (put) the reference.
