### ISSUE TITLE
Compile error when including gcc's <numeric> header after <netlink/cli/utils.h> 

### ISSUE THREAD

**Issue by rdwampler** [thom311/libnl#256]
```
/opt/compiler-explorer/gcc-9.3.0/lib/gcc/x86_64-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/stl_numeric.h:139:9: error: expected unqualified-id
        __init = _GLIBCXX_MOVE_IF_20(__init) + *__first;
               ^
/opt/compiler-explorer/gcc-9.3.0/lib/gcc/x86_64-linux-gnu/9.3.0/../../../../include/c++/9.3.0/bits/stl_numeric.h:140:14: error: expected expression
      return __init;
             ^
<source>:2:16: note: expanded from macro '__init'
#define __init __attribute__((constructor))
```

Since this macro is defined in a public header, I assume it's part of the API so I'm not sure if there is a way to fix this without breaking things. Also, I doubt gcc would accept a patch to change the variable name since identifiers with double underscores are reserved by the C++ standard.

**Comment by thom311** [comment]
I don't understand what the problem here is. `git grep -w __init` doesn't give any results for libnl3.

It would require more details, like a simple reproducer/example. Or a patch/pull-request.

Closing. Please reopen, if you think something should be done.
