### ISSUE TITLE
make check only has a few tests? are the other tests supposed to pass too?

### ISSUE THREAD

**Issue by yifan19** [thom311/libnl#270]
There are bunch of tests in the test folder that get built 
but never gets run when i run make check

* ex: tests/test-genl, tests/test-create* 
Does `check-all` run all these tests? Are these "legacy tests" still relevant? 

I found many of them failing on a yocto project build

Here is the result of `make check`
```
Running suite(s): main
 Abstract addresses
 Netlink attributes
 Clone ematch tree
100%: Checks: 9, Failures: 0, Errors: 0
PASS: tests/check-all
Running suite(s): main
 Direct
100%: Checks: 1, Failures: 0, Errors: 0
PASS: tests/check-direct
==================
All 2 tests passed
```

running `test-genl` 
gives:

```
root@qemux86-64:~/libnl-master# tests/test-genl
Error: Unable to resolve family name
```

**Comment by thom311** [comment]
many of those "tests" are not unit-tests can can run alone. Rather, they are small test programs that can be run for manually testing the code (after all, they configure things in kernel, so they don't run on a random system without modification).

The only unit tests are those that run with `make check`.

It would be great to have more tests (I mean, actual "tests"). In particular, we could use network namespaces to run such tests without root permissions.

I don't think there is anything to do for this issue. Yes, more tests would be great. If you think so too, please open a merge request :) Thank you.
