### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [thom311/libnl#272]
@thom311: It is possible to have a new build?

Currently: libnl 3.5.0
@thom311 thom311 released this Sep 1, 2019 · 47 commits to master since this release 

Thanks in advance.

**Comment by cheng362432** [comment]
release a new_version?

**Comment by thom311** [comment]
libnl 3.6.0 was released.

http://lists.infradead.org/pipermail/libnl/2022-April/002414.html
