### ISSUE TITLE
Cross Compilation Steps

### ISSUE THREAD

**Issue by krunalchauhan637** [thom311/libnl#322]
Hi,
I have phytec Imx6up board.

I need to cross compile this library for above board.
I have use makefile for existing project to cross compile
Require steps for build and also required install steps

If any details required from our end let me know

**Comment by thom311** [comment]
libnl3 uses autotools. I am not familiar with cross compilation, but I think that the usual approach (related to autotools project) applies. I'd recommend to familiarize yourself with autotools and how to build software.
