### ISSUE TITLE
Is the comment for nl_nh_group_info correct?

### ISSUE THREAD

**Issue by irino** [thom311/libnl#356]
When I read PR #332, I found comments that seem incorrect
https://github.com/thom311/libnl/blob/4c39a2ce1b379c4caa8118ba544b53c9bdb3b687/include/netlink/route/nh.h#L19C25-L19C25

```
typedef struct nl_nh_group_info {
	uint32_t nh_id; /*!< VLAN number */
	uint8_t weight; /*!< VLAN QOS value */
} nl_nh_group_info_t;
```
I think the comments should be 

```
typedef struct nl_nh_group_info {
	uint32_t nh_id; /*!< nexthop id */
	uint8_t weight; /*!< weight in nexthop group*/
} nl_nh_group_info_t;
```

**Comment by thom311** [comment]
you are right, looks like a copy+paste error. Should be fixed :)

**Comment by thom311** [comment]
fixed by https://github.com/thom311/libnl/commit/74bffbf6181f9d5afc722ce71c9cc9e48d519dbc

Thanks!!
