### ISSUE TITLE
InvalidFree and InvalidRead in Valgrind when linked against libnl

### ISSUE THREAD

**Issue by Cach30verfl0w** [thom311/libnl#358]
While testing our new networking implementation, which is based on libnl on Linux, i discovered that there seems to be an invalid free and an invalid read somewhere in libnl. I didn't debug it any further yet because libnl is quite large but i figured the stack traces from Valgrind would be pretty helpful for now. Built with GCC 11.4 on Linux x86_64. Tested with and without sanitizers, as well as release- and debug-builds, all yielding the same result(s).
![1](https://github.com/thom311/libnl/assets/88557200/e7e48f26-e8ee-4f56-ac74-0d9ec1a0111e)
![2](https://github.com/thom311/libnl/assets/88557200/3b780c9f-b8de-4ee7-871c-da61576f6e50)

**Comment by KitsuneAlex** [comment]
Can reproduce and confirm that there's something weird going on here.

**Comment by thom311** [comment]
which version are you using?


the backtrace in the screenshot doesn't have all debug symbols enabled. It's not sufficent to understand (or reproduce) the problem. A reproducer would be good. `git-bisect` could find whether this was broken recently.

**Comment by Cach30verfl0w** [comment]
After some further debugging i found the issue in our codebase, sorry for any inconveniences.
