### ISSUE TITLE
Package for RHEL

### ISSUE THREAD

**Issue by dr-vortex** [thom311/libnl#383]
Would it be possible to package libnl for RHEL?

**Comment by thom311** [comment]
it is packaged:

```bash
$ dnf search libnl3
$ dnf install libnl3-devel
```

**Comment by dr-vortex** [comment]
Ah, I see, my bad.

**Comment by thom311** [comment]
> Ah, I see, my bad. I saw on the website "CentOS: never packaged" and jumped to a conclusion.

the web site is very outdated. I don't have access to it, so I cannot fix it. I suggest to ignore it.
