### ISSUE TITLE
The cache manager test is not working (test-cache-mngr.c)

### ISSUE THREAD

**Issue by davidchappelle** [thom311/libnl#70]
I am running Linux Mint 17 and have a freshly built libnl pulled here from github. When I run the test I get the following error:

    $ test-cache-manager "route/addr"
    Unable to add cache route/addr: Unknown or invalid cache type

In tracing through the code I came accross:

     lib/cache_mngt.c
     33 static struct nl_cache_ops *cache_ops;
     34 static NL_RW_LOCK(cache_ops_lock);

So when running the test I end up here:

    lib/cache_mngr.c
    321 int nl_cache_mngr_add(struct nl_cache_mngr *mngr, const char *name,
    322               change_func_t cb, void *data, struct nl_cache **result)
    323 {
    324     struct nl_cache_ops *ops;
    325     struct nl_cache *cache;
    326     int err;
    327 
    328     ops = nl_cache_ops_lookup_safe(name);
    329     if (!ops)
    330         return -NLE_NOCACHE;

So it seems that there is something missing from the test because it is behaving like I am supposed to somehow populate cache ops? Any insights?

**Comment by davidchappelle** [comment]
Ok I think I may have found the issue. It appears that the functions tagged with the __init specifier are not being invoked:

    lib/route/addr.c
    1129 static void __init addr_init(void)
    1130 {
    1131     nl_cache_mngt_register(&rtnl_addr_ops);
    1132 }

**Comment by davidchappelle** [comment]
Doesn't seem to matter what I do, I am not getting ant of these functions linked into my binary which means they are not getting executed on startup to setup the cache ops. How do I force this stuff to get linked in?

**Comment by thom311** [comment]
What is 

    $ test-cache-manager "route/addr"

? Is that something you wrote?

\_\_init is defined as \_\_attribute__((constructor)) (https://gcc.gnu.org/onlinedocs/gcc/Function-Attributes.html). This is a compiler specific extension. gcc and clang support that. Are you using another compiler?

**Comment by davidchappelle** [comment]
test-cache-manager came from the tests directory in this repo (test-cache-mngr.c). Suppose I should have made that clearer. I figured out what the issue was. No symbols are referenced from lib/route/addr.c or route/link.c so as a result addr_init and link_init were not included and thus not invoked. Not sure if the intent of that test is to actually do anything useful though. I was trying to use it as a starting point for using the cache manager.

**Comment by thom311** [comment]
test-cache-mngr links dynamically to the libnl libraries:
 $ libtool --mode=execute ldd ./tests/test-cache-mngr
so, I don't see any reason why addr_init() shouldn't be called.

How did you build test-cache-mngr? Usually you would just type `make check`.

the test functions are unfortunately not unit-test-like test programs that can always run and test something sensible (would be great to have, patches welcome). They are rather some hacked up snippets to demo something and to test it (manually) while implementing it.

Yeah, they should be better... but test-cache-mngr works as expected for me (including calling init_addr()).

**Comment by davidchappelle** [comment]
I guess I am statically linking so that would explain why.
