### ISSUE TITLE
Conflicts between linux/if.h and net/if.h

### ISSUE THREAD

**Issue by davidchappelle** [thom311/libnl#72]
My project is based in c++ and uses boost and a number of other third party libraries. It appears that all of these libraries prefer net/if.h over linux/if.h. As it turns out, there is a conflict between the two. So what I have now that I have integrated libnl with the rest of my project is a bunch of multiple definition errors as follows:

    /usr/include/linux/if.h:143:8: error: redefinition of 'ifmap'
    struct ifmap {
           ^
    /usr/include/net/if.h:111:8: note: previous definition is here
    struct ifmap

Doing a quick grep through the source code of all of my third party libs shows that they all use net/if.h rather than linux/if.h. There are about 8 or 9 libs that include net/if.h. Not a single library out of the dozen or so include linux/if.h.

    $ grep -r "net/if.h" *
    third-party/boost/libs/asio/include/boost/asio/detail/socket_types.hpp:# include <net/if.h>
    third-party/libtorrent-rasterbar/src/enum_net.cpp:#include <net/if.h>
    .
    .
    .

I don't see any way to currently resolve this issue. Is this something that has come up before? There seems to be a long checkered history of conflicts between these two headers.

**Comment by davidchappelle** [comment]
Seems this issue has cropped up in the past with libnl:

    http://lists.infradead.org/pipermail/libnl/2012-April/000525.html

Need to find a solution.

**Comment by davidchappelle** [comment]
I tried the proposed path from that thread and it works. I am going to put together a quick pull request.

**Comment by davidchappelle** [comment]
Ok I have created the patch, pushed it, and submitted a pull request.

**Comment by thom311** [comment]
I merged and closed https://github.com/thom311/libnl/pull/73 .

Hence this issue should be fixed too (right?)


Thanks for stepping up and solve it!!
