### ISSUE TITLE
stack question

### ISSUE THREAD

**Issue by localtracker** [thom311/libnl#76]
Needed to know if there is any way in python/scapy to create a wireless access that links with the scapy TCP/IP stack so I can intercept communications flowing through the stack? What I am aiming to achieve is to create a wlan access point and use scapy to implement a system for sniffing packets sent to that interface and its clients and then choose to reject/accept packets based on rules, think firewall. I am not very skilled in python and my job does'nt even involve infosec or programming. This is a hobby that I have and I don't know as much as some of you guys reading this but I was hoping to find a solution to my problem.

**Comment by thom311** [comment]
I don't know the answer to this question.

libnl is a library to parse/create/send/receive netlink messages. If the larger goal you want to achieve is implemented by doing some form of netlink communication, then you could use libnl to implement that communication.

Try asking this question on an appropriate IRC channel or mailinglist where you have a wider audience. Possibly a scapy channel??

You are also welcome on the libnl mailing list ( libnl@lists.infradead.org ), but I don't know if somebody there can help you.
