### ISSUE TITLE
What license is LibNL distributed in?

### ISSUE THREAD

**Issue by yachtcaptain23** [thom311/libnl#80]
I'm looking at the following files:
external/libnl/include/linux/if_arp.h: 
external/libnl/include/linux/if_bad.h 
external/libnl/include/linux/if_ether.h
external/libnl/lib/route/pktloc.c
external/libnl/src/cls/basic.c 
external/libnl/src/cls/cgroup.c 
external/libnl/src/cls/utils.c 
external/libnl/src/cls/utils.h 
external/libnl/src/nl-addr-add.c 
external/libnl/src/nl-addr-delete.c
external/libnl/src/nl-addr-list.c
external/libnl/src/nl-cls-add.c 

And they're all distributed with GPLv2. Looking at the COPYING file, it says that LibNL is distributed as LGPL. 

If someone familiar with licensing can explain the licensing for this project, that would be immensely helpful :smiley:

**Comment by tgraf** [comment]
On 06/30/15 at 02:43pm, Albert Wang wrote:
> I'm looking at the following files:
> external/libnl/include/linux/if_arp.h: 
> external/libnl/include/linux/if_bad.h 
> external/libnl/include/linux/if_ether.h
> external/libnl/lib/route/pktloc.c
> external/libnl/src/cls/basic.c 
> external/libnl/src/cls/cgroup.c 
> external/libnl/src/cls/utils.c 
> external/libnl/src/cls/utils.h 
> external/libnl/src/nl-addr-add.c 
> external/libnl/src/nl-addr-delete.c
> external/libnl/src/nl-addr-list.c
> external/libnl/src/nl-cls-add.c 
> 
> And they're all distributed with GPLv2. Looking at the COPYING file, it says that LibNL is distributed as LGPL. 
> 
> If someone familiar with licensing can explain the licensing for this project, that would be immensely helpful :smiley: 

The library is LGPL. Most of the examples code is GPLv2.
The GPLv2 headers are kernel header copies for easier building.

**Comment by yachtcaptain23** [comment]
We checked the makefile to confirm that you're correct :+1: :bow:
