### ISSUE TITLE
vlan_put_attrs missing IFLA_VLAN_PROTOCOL 

### ISSUE THREAD

**Issue by ElSzymono** [thom311/libnl#90]
The vlan_put_attrs function in lib/route/link/vlan.c is missing:
```
	if (vi->vi_mask & VLAN_HAS_ID)
		NLA_PUT_U16(msg, IFLA_VLAN_ID, vi->vi_vlan_id);

+	if (vi->vi_mask & VLAN_HAS_PROTOCOL)
+		NLA_PUT_U16(msg, IFLA_VLAN_PROTOCOL, vi->vi_protocol);

	if (vi->vi_mask & VLAN_HAS_FLAGS) {
		struct ifla_vlan_flags flags = {
			.flags = vi->vi_flags,
			.mask = vi->vi_flags_mask,
		};
```
Because of this the protocol value set by rtnl_link_vlan_set_protocol is not passed to the kernel and only 802.1Q interfaces can be created.

**Comment by thom311** [comment]
Fixed. See https://github.com/thom311/libnl/pull/91
